### ISSUE TITLE
Preserve Entity Reference doesn't seem to be working

### ISSUE THREAD

**Issue by jsbiff** [EXIficient/exificient-gui#1]
Exificient-Gui Java 1.0.0

I have an XHTML test document. It includes the &trade; html entity reference. I tested round tripping from the original xhtml to EXI, back to xml, and even though, in the advanced encoding options I had selected, "Include EXI Options as part of the EXI header" and "Retain entity references as ER events", upon decoding, the resulting xml file had the &trade; replaced with the TM unicode character.

I'm not sure if this is an encoding problem, or a decoding problem. It could be that the entity reference was preserved in the binary EXI data, but then during decoding, it did not honor that setting and restore the entity reference, but instead resolved it to the character.

**Comment by danielpeintner** [comment]
I believe once you go through APIs like SAX (or others) there is no way to guarantee preserving "™" instead of the Unicode characters counterpart. I don't even know whether that makes sense... the characters are the "same" ... just differently visualized.

To achieve preservation of such characters you might need a special XML encoder that does that job for you.

What do you try to achieve with doing so?

**Comment by jsbiff** [comment]
> 

Daniel, well, it's not so important for the trade ER, but if it's doing that for trade, I'm worried it would do it for, say, lt, gt, or amp, which could cause the regenerated xml to be invalid. But, perhaps the APIs like SAX are aware of what entities MUST remain entities in order to represent literal chars that would break xml. I will do some testing on that.

**Comment by jsbiff** [comment]
> > 
> 
> Daniel, well, it's not so important for the trade ER, but if it's doing that for trade, I'm worried it would do it for, say, lt, gt, or amp, which could cause the regenerated xml to be invalid. But, perhaps the APIs like SAX are aware of what entities MUST remain entities in order to represent literal chars that would break xml. I will do some testing on that.

Ok, so I just ran a test, and yes, it does appear it's smart enough that entities that would break XML if resolved to their literal chars, do get output as xml/html entities - even without the option to preserve the entity reference. Sorry, I should have thought to check that before filing the issue. I saw that my trade ER got resolved, and jumped to the assumption that meant all entities got resolved. I should have thought to test first.
